### ISSUE TITLE
Ardu_ECU version 10 is not compiling.

### ISSUE THREAD

**Issue by dstromeng** [Jehanzeb1973/Ardu_ECU#3]
Hi @Jehanzeb1973 
I have been following this project and was able to make a breadboard model of this ecu. The version 10 of the code wasn't able to compile and is throwing errors.
I was able to successfully compile and upload version 9 though.

**Comment by Jehanzeb1973** [comment]
What are the errors you are getting ? There is no new library being used in version 10. The only change is that OLED Display code has been commented out and HTML page4 is updated.

**Comment by Jehanzeb1973** [comment]
I have just recompiled the version 10 to ensure that i have not uploaded something wrong and it compiled fine on my computer. I have zipped and uploaded it again. Check if this helps
